name:                sa
version:             0.1.0.0
github:              "DexterLB/sa"
license:             BSD3
author:              "dexterlb"
maintainer:          "dexterlb@qtrp.org"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/DexterLB/sa#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12 && < 0.13

library:
  source-dirs: src

executables:
  sa-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sa

tests:
  sa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sa
